name: Test Deploy to Amazon ECS

on:
  push:
    branches:
      - Feat/FM-9

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: filmeet

    env:
      AWS_REGION: ap-northeast-2
      AWS_DEFAULT_REGION: ap-northeast-2

    steps:
      # 1️⃣ 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ AWS CLI 인증 설정
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # 3️⃣ Java 17 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 4️⃣ Gradle 권한 설정
      - name: Set permissions for gradlew
        run: chmod +x ./gradlew

      # 5️⃣ Docker 이미지 빌드 및 푸시 (Jib)
      - name: Build and Push Docker Image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: ./gradlew jib --stacktrace

      # 6️⃣ ECS 서비스 업데이트
      - name: Update ECS Service
        run: |
          aws ecs update-service \
            --cluster filmeet-cluster \
            --service filmeet-service \
            --force-new-deployment --debug
