name: Test Deploy to Amazon ECS

on:
  push:
    branches:
      - Feat/FM-9

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Java 17 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3️⃣ Gradle 권한 설정
      - name: Set permissions for gradlew
        run: chmod +x ./gradlew
        working-directory: filmeet

      # 4️⃣ Docker 이미지 빌드 및 푸시
      - name: Build and Push Docker Image
        run: ./gradlew jib
        working-directory: filmeet

      # 5️⃣ ECS 서비스 업데이트
      - name: Update ECS Service
        run: |
          aws ecs update-service \
            --cluster filmeet-cluster \
            --service filmeet-service \
            --force-new-deployment
