name: Test Deploy to Amazon ECS

on:
  push:
    branches:
      - Feat/FM-9

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ 디버깅: 현재 디렉토리 확인
      - name: Debug Working Directory
        run: pwd

      - name: List Files in Root
        run: ls -al

      # 3️⃣ Gradle 관련 작업 디렉토리 설정
      - name: Set permissions for gradlew
        run: chmod +x ./gradlew
        working-directory: filmeet

      # 4️⃣ Docker 이미지 빌드 및 ECR 푸시
      - name: Build and Push Docker Image
        run: ./gradlew jib
        working-directory: filmeet

      # 5️⃣ ECS 서비스 업데이트
      - name: Update ECS Service
        run: |
          aws ecs update-service \
            --cluster filmeet-cluster \
            --service filmeet-service \
            --force-new-deployment
