name: Deploy on PR Merge to Main

on:
  pull_request:
    types: [closed]  # PR이 닫힐 때 실행
    branches:
      - main  # main 브랜치에 머지될 때 작동
  push:
    branches:
      - Feat/FM-99-1
jobs:
  deploy:
    if: >
      (github.event_name == 'push') ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest  # GitHub Actions 실행 환경 설정

    # 작업 디렉토리 기본값 설정
    defaults:
      run:
        working-directory: filmeet  # 'filmeet' 디렉토리에서 명령 실행

    # 전역 환경 변수 설정
    env:
      AWS_REGION: ap-northeast-2  # AWS 리전 설정

    steps:
      # 1️⃣ 저장소 체크아웃
      - name: 소스 코드 체크아웃
        uses: actions/checkout@v3

      # 2️⃣ AWS 자격 증명 설정
      - name: AWS 자격 증명 구성
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # AWS Access Key ID (GitHub Secrets에서 가져옴)
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # AWS Secret Access Key (GitHub Secrets에서 가져옴)
          aws-region: ${{ env.AWS_REGION }}  # AWS 리전 설정

      # 3️⃣ Java 17 설치
      - name: Java 17 설정
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # 사용하려는 Java 버전
          distribution: 'temurin'  # Java 배포판 설정

      # 4️⃣ Gradle 실행 권한 부여
      - name: Gradle 실행 권한 설정
        run: chmod +x ./gradlew  # Gradle Wrapper에 실행 권한 부여

      # 5️⃣ Amazon ECR에 로그인
      - name: Amazon ECR 로그인
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1  # ECR에 로그인하여 인증 토큰 획득

      # Firebase 서비스 계정 JSON 복원
      - name: Create Firebase JSON file from Secrets
        run: |
          echo "${{ secrets.FIREBASE_CONFIG }}" > firebase-service-account.json

      # 5️⃣ Docker 이미지 빌드 및 푸시
      - name: Docker 이미지 빌드 및 푸시
        run: ./gradlew jib --no-build-cache
        env:
          AWS_ECR_PASSWORD: ${{ steps.login-ecr.outputs.ecr-login-password }}
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          SPRING_DATA_REDIS_HOST: ${{ secrets.SPRING_DATA_REDIS_HOST }}
          SPRING_DATA_REDIS_PORT: ${{ secrets.SPRING_DATA_REDIS_PORT }}
          SPRING_CLOUD_AWS_S3_BUCKET: ${{ secrets.SPRING_CLOUD_AWS_S3_BUCKET }}
          SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID: ${{ secrets.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID }}
          SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: ${{ secrets.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET }}
          SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_ID: ${{ secrets.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_ID }}
          SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_SECRET: ${{ secrets.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_SECRET }}
          KOBIS_APIKEY: ${{ secrets.KOBIS_APIKEY }}
          KMDB_APIKEY: ${{ secrets.KMDB_APIKEY }}
          OMDB_APIKEY: ${{ secrets.OMDB_APIKEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_VALIDITY_ACCESS: ${{ secrets.JWT_VALIDITY_ACCESS }}
          JWT_VALIDITY_REFRESH: ${{ secrets.JWT_VALIDITY_REFRESH }}

      # 6️⃣ ECS 서비스 업데이트
      - name: ECS 서비스 업데이트
        run: |
          aws ecs update-service \
            --cluster filmeet-cluster \
            --service filmeet-service \
            --force-new-deployment \
            --deployment-configuration maximumPercent=200,minimumHealthyPercent=75 \
            --health-check-grace-period 300